name: yoon
favicon: null
layout_spectrum: 0.7414941878523678
typography_spectrum: 0.48907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#343434'
    - '#fbfbfb'
    - '#888888'
    - '#bdbdbd'
    - '#dddddd'
  brandStrength: 0.7087585730478168
  lightness: 0.16211295640096068
  saturation: 0.4222279889509082
  rhythmicContrast: 0.3800338471774012
purpose: []
